### ISSUE TITLE
Still developing? 

### ISSUE THREAD

**Issue by marklescroart** [snake-biscuits/bsp_tool#1]
Nice tool you've built here! I'm a researcher, interested in building virtual environments for people to explore, such that I can scan their brains while they navigate through the maps. The goal is to learn something about how the brain encodes navigation. This tool could put a lot more maps at my disposal for my experiments (doing bsp export / conversion manually through e.g. nem's tools is tedious and doesn't work well on linux / mac, which are my primary computers). So - out of curiosity - are you still developing this? There are a few small bugs in the code that I've caught (could submit a PR for those if you're interested), and there are some other things that I haven't had time to dig into (some geometry errors for some maps, no material exporter implemented yet). But before I get too deep here, I wanted to know if this is an ongoing project that you plan to improve, or just a quickie side project.

Cheers,
Mark

**Comment by snake-biscuits** [comment]
This is very much a side project, I tend to work on multiple things at once but I never really close projects. They're always open, progress is usually just slow and uncommon.

I'd be happy to look at any bugs you've spotted when I find the time, though don't expect any huge progress as I don't have as much time on my hands as when I started this project.

I have been looking for an excuse to do more with this code, I just haven't had much in the way of a clear goal. Also, sorry for not responding sooner! (I know I rarely check my e-mail properly but 8 months is bad!)
