### ISSUE TITLE
Cannot load entities lump

### ISSUE THREAD

**Issue by lf94** [snake-biscuits/bsp_tool#10]
I made a small script to play around with bsp_tool:

```
from bsp_tool import load_bsp
from bsp_tool.branches.respawn.apex_legends import LUMP

file = "/home/lee/Code/Mine/Analysis/ApexLegends/Maps/KingsCanyon/mp_rr_canyonlands_staging.bsp"
bsp = load_bsp(file)
bsp.read_lump(LUMP.ENTITIES)
```
Note I do have the `...0000.bsp_lump`.

But I'm unable to retrieve the entities lump:

```
$ python3 test.py
Loading mp_rr_canyonlands_staging.bsp (rBSP version 49)...
ERROR PARSING TEXDATA:
TEXDATA lump is an unusual size (400 / 36). Wrong engine branch?
Loaded  mp_rr_canyonlands_staging.bsp
Traceback (most recent call last):
  File "/home/lee/Code/Others/bsp_tool/test.py", line 6, in <module>
    bsp.read_lump(LUMP.ENTITIES)
  File "/home/lee/Code/Others/bsp_tool/bsp_tool/respawn.py", line 29, in read_lump
    self.file.seek(self.branch.lump_header_address[LUMP])
ValueError: seek of closed file
```

After this I'm going to probably export the vertices to see some point clouds (as you've done in `lump_analysis.py`).

Have you gotten chunks of the level to render with planes? Do you know how LOD is handled?

**Comment by snake-biscuits** [comment]
The read_lump method is used behind the scenes to load lumps into the RespawnBsp object
You can access the entities lump with `bsp.ENTITIES`
I can see how that's not intuitive though

At present bsp_tool loads all lumps into memory if the given filename exists,
I may be moving towards loading lumps a little more dynamically in future though

I have converted maps to `.obj` models before, but they have so many vertices it freezes Blender to load them
LoD isn't something I've looked into either

**Comment by lf94** [comment]
Ah ok, so `read_lump` is not the intended way to read lumps then I guess?

Is it expected all the bsp's lumps are in the same directory? In my example, I only had the `0000` lump, but because I only intended to read that one. I'm assuming after your comment, it is expected.

I'm guessing you're not using the BSP tree to export only portions of the map? :slightly_smiling_face:

**Comment by snake-biscuits** [comment]
Yes it's expected that any `.bsp_lump` files are in the same folder as the target `.bsp`
to load just the `0000` lump you could just open it in notepad, it's just text

Also I don't know if the Respawn branch uses BSP trees, it seems to me they might unload some meshes but idk if the conditions are defined in a bsp tree or not
