### ISSUE TITLE
Inverted "normals" in rBSP (mp_rr_aquaduct at least)

### ISSUE THREAD

**Issue by mrsteyk** [snake-biscuits/bsp_tool#14]
When you load an mp_rr_aquaduct and enable backface culling - all of the normals or order of verticies are inverted rendering the result mesh unusable (as-is) in most real-world case scenarios like importing the FBX in Hammer 2

Pic:

![image](https://user-images.githubusercontent.com/10615163/127345664-97735249-4876-4199-87a9-c2adc0c99ac7.png)

**Comment by snake-biscuits** [comment]
Looks like I reversed the winding order for triangles for Titanfall 1 & 2, but not Apex
Pushing out a fix now
