### ISSUE TITLE
how use x360.py?

### ISSUE THREAD

**Issue by metalex10** [snake-biscuits/bsp_tool#153]
hi friend how use funtion make_big_endian and  convert_versioned

and more instructions

**Comment by snake-biscuits** [comment]
`branches.x360` is a utility for bulk conversion of `LumpClasses` to `big-endian`
It only affects `LumpClasses`, which are used for parsing / writing lump bytes

**`branches.x360` does not transform lumps or their bytes, it just generates "definitions" so we can parse them**

I'm assuming you're looking for a way to convert a `little-endian` `.bsp` to `big-endian`
Since you've been asking about that in:
 * #79
 
`branches.x360` is not for conversion, tools for porting maps across formats are in `extensions.convert`
**I haven't tried to make a tool for big-endian conversion yet as it would be fairly complex**

**Comment by metalex10** [comment]
is not convert , is possible swap bytes because you make a tool to load little endian maps, so you load little endian, is possible save to big endian not?

**Comment by snake-biscuits** [comment]
It's possible, but not for every lump
DisplacementInfo, Primitive & Leaf aren't supported in big-endian

While is possible to have a map with no DisplacementInfo & Primitives, Leaves are essential
To fix this we'd need big-endian bitfields, which change the order or Most Significant & Least significant bits

basically, branches.common.BitField needs an upgrade

**Comment by snake-biscuits** [comment]
#113 has some more details on this

**Comment by metalex10** [comment]
ok but is possible make or a tratament for convert with the program?
MakeGameData?
MakeMaps?

https://github.com/metalex10/SourceEngine2007/blob/master/src_main/utils/xbox/MakeGameData/MakeMaps.cpp

**Comment by snake-biscuits** [comment]
> metalex10/SourceEngine2007@`master`/src_main/utils/xbox/MakeGameData/MakeMaps.cpp

https://github.com/metalex10/SourceEngine2007/blob/master/src_main/utils/xbox/MakeGameData/MakeMaps.cpp#L97
```c++
//-----------------------------------------------------------------------------
// Purpose: Generate .360 bsp
//-----------------------------------------------------------------------------
bool CreateTargetFile_BSP( const char *pSourceName, const char *pTargetName, bool bWriteToZip )
```

Looks like it might be possible to convert maps w/ the Source Engine xbox utils
You should look around to see if anyone else has tried & talked about it online
It's possible these tools are for the Xbox (not 360) version of HL2 though

Most console related code would be locked down & not available publically
This is the case for Havok physics
Console developers are known for being extremely strict about this, **especially** Microsoft

**Comment by snake-biscuits** [comment]
> Looks like it might be possible to convert maps w/ the Source Engine xbox utils

Actually, looking closer, I can't tell if this function flips endianness

**Comment by snake-biscuits** [comment]
> Actually, looking closer, I can't tell if this function flips endianness

It does, by calling this function (not in the 2007 SDK):
https://github.com/ValveSoftware/source-sdk-2013/blob/master/sp/src/utils/common/bsplib.cpp#L4575
```c++
//-----------------------------------------------------------------------------
//  For all lumps in a bsp: Loads the lump from file A, swaps it, writes it to file B.
//  This limits the memory used for the swap process which helps the Xbox 360.
//
//	NOTE: These lumps will be written to the file in exactly the order they appear here,
//	so they can be shifted around if desired for file access optimization.
//-----------------------------------------------------------------------------
bool SwapBSPFile( const char *pInFilename, const char *pOutFilename, bool bSwapOnLoad, VTFConvertFunc_t pVTFConvertFunc, VHVFixupFunc_t pVHVFixupFunc, CompressFunc_t pCompressFunc )
```

That function implies that they ran the tools on Xbox360 hardware (devkits?)

**Comment by snake-biscuits** [comment]
Porting maps isn't at all related to `branches.x360`
Closing this issue.

If you have more questions about Xbox360 map ports go here:
 * #79

**Comment by snake-biscuits** [comment]
> That function implies that they ran the tools on Xbox360 hardware (devkits?)

I misread the description of the function
What's more likely is they meant swapping `.bsp` endian-ness at "compile time" saves the Xbox360 console work
So it's part of optimisation in the map creation process (which would presumably be done on little-endian workstations)

The Xbox360 being big-endian, vs most PC architectures being little-endian seemed like common knowledge to me
Probably why I assumed that wouldn't need mentioning, but function descriptions aren't for people that know what they do.
