### ISSUE TITLE
Any progress on save_as() function ?

### ISSUE THREAD

**Issue by miifanboy** [snake-biscuits/bsp_tool#19]
I am working on a program which automatically adds an eventlistener to any given csgo .bsp file. I have already made a progress on adding the entities to the bsp and the only thing left is to save the map to a new bsp file. I just wanted to know if any progress was made in the past 4 months ?

**Comment by snake-biscuits** [comment]
Most progress on that will be in #15 
atm properly saving changes would require a bit of a refactor due to how I've made some things
It is on my list tho, and I intend to do a few of these refactors soon

**Comment by snake-biscuits** [comment]
Just tested the latest commit on csgo maps and save_as appears to be stable.
You should be able to edit and save changes to CS:GO maps now.
Let me know if you run into any problems

**Comment by snake-biscuits** [comment]
Since I haven't heard anything back in the past 3 weeks I'm going to assume this solved the issue
#20 might be creating some issues atm but that's a high priority and should be solved soon™
