### ISSUE TITLE
Is 29 (LUMP_PHYSCOLLIDE) really unused?

### ISSUE THREAD

**Issue by lf94** [snake-biscuits/bsp_tool#6]
https://github.com/snake-biscuits/bsp_tool/blob/56c425188073178d7d605c15b24be8e691ca831f/bsp_tool/branches/respawn/apex_legends.py#L53

Appears this is unused, but I'm not sure if that was just put there in a haste or is actually reality. I could not find any information on LUMP_PHYSLEVEL which I suspect may be the alternative lump which holds collision data.

**Comment by snake-biscuits** [comment]
Both Titanfall 1 & 2 store lump 29 externally in `<map_name.bsp>.001d.bsp_lump`
None of the Apex .bsp's I've checked have this file
I've checked the headers in `mp_rr_olympus.bsp` for lump 29 & it's empty, so it's not in the .bsp either
Best I can tell, the Apex Legends branch just doesn't use this lump

.bsps checked:
```
mp_rr_canyonlands_64k_x_64k   KING'S CANYON
mp_rr_canyonlands_mu1
mp_rr_canyonlands_mu1_night   SHADOW ROYALE
mp_rr_canyonlands_mu2
mp_rr_canyonlands_staging     FIRING RANGE
mp_rr_desertlands_64k_x_64k   WORLD'S EDGE
mp_rr_desertlands_mu1         WINTER EXPRESS?
mp_rr_olympus                 OLYMPUS
```

**Comment by lf94** [comment]
Interesting, thank you for the check!
Perhaps it's in the BSP but under a different lump? I did see a few unknowns in there.

**Comment by lf94** [comment]
FWIW I plan to start investigating where collision is defined today. I'll update you if anything. End goal is exporting collision to .obj or similar so it's viewable in Blender or similar.

**Comment by snake-biscuits** [comment]
I'll definitely be interested to hear what you find!
I'm slowly exploring more of the rBSP format, starting from the first Titanfall but I haven't touched physics yet
