### ISSUE TITLE
rBSP version is now 49

### ISSUE THREAD

**Issue by lf94** [snake-biscuits/bsp_tool#9]
canyonlands_staging uses rBSP version 49, which is even newer than the 48 noted in the file.

**Comment by snake-biscuits** [comment]
I've added the version number in so `bsp_tool.load_bsp` will load version 49 rBSP
The only change in the format I can see so far is the TEXDATA lump has changed size again
I'll work out systems for correctly loading different lump versions later but for now load_bsp will correctly identify v49 rBSP

**Comment by lf94** [comment]
I think for most purposes, only supporting the latest version is the most sane thing to do.
