### ISSUE TITLE
ENTITIES values contained symbols "{" "}" don't read

### ISSUE THREAD

**Issue by vic7or777** [snake-biscuits/bsp_tool#91]
quake2 map tltf.bsp has worldspawn message:
"'The Longest Three Feet' for Q2 DM by Briareos {Moo}"
[http://tastyspleen.net/~quake2/baseq2/maps/tltf.bsp](url)
its dont read by bsp_tool, sample code:

`from os import environ as env`
`from bsp_tool import load_bsp`
`file = rf"{env['USERPROFILE']}\Downloads\tltf.bsp"`
`for ent in load_bsp(file).ENTITIES:`
`    if ent['classname'] == 'worldspawn':`
`        print(ent)`

result:
`{'gravity': '700', 'skyrotate': '1', 'sky': 'space1', 'classname': 'worldspawn'}`

![image](https://user-images.githubusercontent.com/5280417/233842590-4910b66d-ea8b-490d-964b-624eb33e2be4.png)

**Comment by snake-biscuits** [comment]
I am surprised that's legal, but Quake 2 can load this map fine
This one will take some work

**Comment by snake-biscuits** [comment]
Fixed in https://github.com/snake-biscuits/bsp_tool/commit/7e99b44f09377f6d79210bb0edf37fdb6accdd50
```python
>>> import bsp_tool
>>> tltf = bsp_tool.load_bsp("E:/Mod/QuakeII/vkquake2-1.5.8_win64/baseq2/maps/tltf.bsp")
>>> tltf.ENTITIES.search(classname="worldspawn")[0]
{'skyaxis': '90 0 90', 'message': "'The Longest Three Feet' for Q2 DM by Briareos {Moo}",
 'gravity': '700', 'skyrotate': '1', 'sky': 'space1', 'classname': 'worldspawn'}
>>> tltf.ENTITIES.search(classname="info_player_start")[0]
{'angle': '134', 'origin': '-426 60 550', 'classname': 'info_player_start'}
```
You'll have to use the latest GitHub version
I've made too many changes to make a patch release for PyPI
`0.5.0` should only be a few refactors away, but don't hold your breath
